<?php

namespace Kubernetes\Model\Io\K8s\Api\Discovery\V1;

use \KubernetesRuntime\AbstractModel;

/**
 * EndpointSlice represents a set of service endpoints. Most EndpointSlices are
 * created by the EndpointSlice controller to represent the Pods selected by
 * Service objects. For a given service there may be multiple EndpointSlice objects
 * which must be joined to produce the full set of endpoints; you can find all of
 * the slices for a given service by listing EndpointSlices in the service's
 * namespace whose `kubernetes.io/service-name` label contains the service's name.
 */
class EndpointSlice extends AbstractModel
{
    /**
     * addressType specifies the type of address carried by this EndpointSlice. All
     * addresses in this slice must be the same type. This field is immutable after
     * creation. The following address types are currently supported: * IPv4:
     * Represents an IPv4 Address. * IPv6: Represents an IPv6 Address. * FQDN:
     * Represents a Fully Qualified Domain Name. (Deprecated) The EndpointSlice
     * controller only generates, and kube-proxy only processes, slices of addressType
     * "IPv4" and "IPv6". No semantics are defined for the "FQDN" type.
     *
     * @var string
     */
    public $addressType = null;

    /**
     * APIVersion defines the versioned schema of this representation of an object.
     * Servers should convert recognized schemas to the latest internal value, and may
     * reject unrecognized values. More info:
     * https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
     *
     * @var string
     */
    public $apiVersion = 'discovery.k8s.io/v1';

    /**
     * endpoints is a list of unique endpoints in this slice. Each slice may include a
     * maximum of 1000 endpoints.
     *
     * @var Endpoint[]
     */
    public $endpoints = null;

    /**
     * Kind is a string value representing the REST resource this object represents.
     * Servers may infer this from the endpoint the client submits requests to. Cannot
     * be updated. In CamelCase. More info:
     * https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
     *
     * @var string
     */
    public $kind = 'EndpointSlice';

    /**
     * Standard object's metadata.
     *
     * @var \Kubernetes\Model\Io\K8s\Apimachinery\Pkg\Apis\Meta\V1\ObjectMeta
     */
    public $metadata = null;

    /**
     * ports specifies the list of network ports exposed by each endpoint in this
     * slice. Each port must have a unique name. Each slice may include a maximum of
     * 100 ports. Services always have at least 1 port, so EndpointSlices generated by
     * the EndpointSlice controller will likewise always have at least 1 port.
     * EndpointSlices used for other purposes may have an empty ports list.
     *
     * @var EndpointPort[]
     */
    public $ports = null;
}

